
-- DEV 2019 ENV
-- -------------------- CREATE DB ---------------------------------------
CREATE DATABASE BRAHMA_V1_DEV;
CREATE DATABASE BRAHMA_V1_DEV_AG;
CREATE DATABASE BRAHMA_V1_DEV_PT;
CREATE DATABASE BRAHMA_V1_SIT;
CREATE DATABASE BRAHMA_V1_SIT_NA;
CREATE DATABASE BRAHMA_V1_BACKTESTING;
CREATE DATABASE BRAHMA_V1_BACKTESTING_AG;

-- --------------------- GRANT DB ----------------------------------------
-- GRANT ALL ON BRICS1_V1_DEV.* TO 'devFinnovesh'@'%' IDENTIFIED BY '6aGkGtfNnGz294m';
GRANT ALL PRIVILEGES ON BRAHMA_V1_DEV.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_DEV_AG.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_DEV_PT.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_SIT.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_SIT_NA.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_BACKTESTING.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BRAHMA_V1_BACKTESTING_AG.* TO 'devFinnovesh'@'%' WITH GRANT OPTION;

-- ------------------- SHOW DB ------------------------------------------
SHOW DATABASES;

-- ------------------- DROP DB --------------------------------------------
DROP DATABASE BRAHMA_V1_SIT;
DROP DATABASE BRAHMA_V1_DEV_PT;