-- USE BRAHMA_V1_PRD;
-- USE BRAHMA_V1_PRD_NA;


-- DROP TABLES
-- -------------------------------------------------------------------------
-- DROP TABLE CONFIG;
-- DROP TABLE LIVE_ACCOUNTS;
-- DROP TABLE POSITION;
-- DROP TABLE ORDERS;
-- DROP TABLE POSITIONS_TRACKING;
-- DROP TABLE POSITIONS_BACK_UP;
-- DROP TABLE POSITIONS_TRACKING_BACK_UP;
-- DROP TABLE TRACKER;

-- USE BRAHMA_V1_PRD;
-- --------------------- TABLE CONFIG ------------------------------------
CREATE TABLE CONFIG (
  ID int NOT NULL AUTO_INCREMENT,
  CONFIG_KEY VARCHAR(1000) NOT NULL,
  CONFIG_VALUE VARCHAR(1000) NOT NULL,
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);

-- USE BRAHMA_V1_PRD;
-- --------------------- TABLE LIVE_ACCOUNTS ------------------------------------
CREATE TABLE LIVE_ACCOUNTS (
  LIVE_STRATEGY_ID int NOT NULL AUTO_INCREMENT,
  CLUSTER_ID VARCHAR(100) NOT NULL,
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  IS_ACTIVE tinyint DEFAULT '1',
  PRIMARY KEY (LIVE_STRATEGY_ID)
);

-- USE BRAHMA_V1_PRD_NA;
-- --------------------- TABLE TRACKER ------------------------------------
CREATE TABLE TRACKER(
    SYMBOL VARCHAR(30) PRIMARY KEY,
	ACCOUNT VARCHAR(30),
    QTY_SELL VARCHAR(30),
    SP_SELL VARCHAR(30),
    CURRENT_UNDERLYING VARCHAR(30),
    NET_PNL VARCHAR(30),
    NET_PNL_PCT VARCHAR(30),
	MARGIN_USED VARCHAR(30),
    POSITIONS_MATCHED VARCHAR(30),
    POSITIONS_CLOSED VARCHAR(30),
    POSITIONS_COUNT_DB VARCHAR(30),
	POSITIONS_COUNT_BROKER VARCHAR(30),
    QTY_COUNT_DB VARCHAR(30),
    QTY_COUNT_BROKER VARCHAR(30),
    RAG VARCHAR(30),
    REFRESH_INTERVAL VARCHAR(30),
    MARGIN_USED_BROKER VARCHAR(30),
    EXECUTION_IV VARCHAR(30),
    CURRENT_IV VARCHAR(30),
    STOPLOSS VARCHAR(30),
    TARGET VARCHAR(30),
    PARAMS TEXT,
    LAST_UPDATED_TIME VARCHAR(30)
);

-- --------------------- TABLE CONFIG ------------------------------------
CREATE TABLE CONFIG (
  ID int NOT NULL AUTO_INCREMENT,
  CONFIG_KEY VARCHAR(1000) NOT NULL,
  CONFIG_VALUE VARCHAR(1000) NOT NULL,
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);


-- --------------------- TABLE SIGNALS ------------------------------------
CREATE TABLE SIGNALS (
  ID int NOT NULL AUTO_INCREMENT,
  SIGNAL_ID varchar(50) NOT NULL,
  SIGNAL_GROUP_ID varchar(50) NOT NULL,
  SYMBOL varchar(10) NOT NULL,
  EXPIRY_DATE  varchar(10) NOT NULL,
  STRIKE_PRICE int NOT NULL,
  CONTRACT_TYPE varchar(30) NOT NULL,
  INSTRUMENT_TYPE ENUM ('PUT','CALL','FUTURES') NOT NULL,
  TRANSACTION_TYPE ENUM ('BUY','SELL') NOT NULL,
  EXECUTION_PRICE decimal(20,5) NOT NULL,
  PARAMS JSON,
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);
CREATE  INDEX SIGNAL_ID_INDEX ON SIGNALS (SIGNAL_ID);
CREATE  INDEX SIGNAL_GROUP_ID_INDEX ON SIGNALS (SIGNAL_GROUP_ID);

-- --------------------- TABLE POSITION ------------------------------------
CREATE TABLE POSITION (
  ID int NOT NULL AUTO_INCREMENT,
  SIGNAL_ID varchar(20) NOT NULL,
  SIGNAL_GROUP_ID varchar(20) NOT NULL,
  POSITION_ID varchar(20) NOT NULL,
  POSITION_GROUP_ID varchar(20) NOT NULL,
  MONEYNESS varchar(20) NOT NULL,
  SYMBOL varchar(10) NOT NULL,
  EXPIRY_DATE  varchar(10) NOT NULL,
  STRIKE_PRICE int NOT NULL,
  INSTRUMENT_TYPE ENUM ('PUT','CALL','FUTURES') NOT NULL,
  TRANSACTION_TYPE ENUM ('BUY','SELL') NOT NULL,
  ORDER_TYPE ENUM ('MARKET','LIMIT') NOT NULL,
  CONTRACT_TYPE varchar(30) NOT NULL,
  NUM_LOTS int NOT NULL,
  LOT_SIZE int NOT NULL,
  QUANTITY int NOT NULL,
  IS_ACTIVE bool NOT NULL DEFAULT 1,
  MARGIN_OVERALL decimal(20,2) NOT NULL,
  ENTRY_PRICE decimal(20,2) NOT NULL,
  EXIT_PRICE decimal(20,2),
  PARAMS JSON,
  REALIZED_PNL decimal(20,2),
  REALIZED_PNL_GROUP decimal(20,2),
  REALIZED_PNL_OVERALL decimal(20,2),
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);
CREATE  INDEX POSITION_SIGNAL_ID_INDEX ON POSITION (SIGNAL_ID);
CREATE  INDEX POSITION_SIGNAL_GROUP_ID_INDEX ON POSITION (SIGNAL_GROUP_ID);
CREATE  INDEX POSITION_ID_INDEX ON POSITION (POSITION_ID);
CREATE  INDEX POSITION_GROUP_ID_INDEX ON POSITION (POSITION_GROUP_ID);
CREATE  INDEX SYMBOL_INDEX ON POSITION (SYMBOL);
CREATE  INDEX CONTRACT_TYPE_INDEX ON POSITION (CONTRACT_TYPE);


-- --------------------- TABLE ORDERS ------------------------------------
CREATE TABLE ORDERS (
  ID int NOT NULL AUTO_INCREMENT,
  ORDER_ID varchar(50) NOT NULL,
  ORDER_GROUP_ID varchar(50) NOT NULL,
  POSITION_ID varchar(50) NOT NULL,
  POSITION_GROUP_ID varchar(50) NOT NULL,
  BROKER_ORDER_ID varchar(50) NOT NULL,
  BROKER_ORDER_STATUS varchar(50) NOT NULL,
  SYMBOL varchar(10) NOT NULL,
  EXPIRY_DATE  varchar(25) NOT NULL,
  STRIKE_PRICE int NOT NULL,
  INSTRUMENT_TYPE ENUM ('PUT','CALL','FUTURES') NOT NULL,
  TRANSACTION_TYPE ENUM ('BUY','SELL') NOT NULL,
  ORDER_TYPE ENUM ('MARKET','LIMIT') NOT NULL,
  CONTRACT_TYPE varchar(30) NOT NULL,
  NUM_LOTS int NOT NULL,
  LOT_SIZE int NOT NULL,
  QUANTITY int NOT NULL,
  IS_SUCCESS bool NOT NULL DEFAULT 1,
  MARGIN_OVERALL decimal(20,2) NOT NULL,
  EXECUTION_PRICE decimal(20,2) NOT NULL,
  PARAMS JSON,
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);
CREATE  INDEX ORDER_ID_INDEX ON ORDERS (ORDER_ID);
CREATE  INDEX ORDER_GROUP_ID_INDEX ON ORDERS (ORDER_GROUP_ID);
CREATE  INDEX POSITION_ID_INDEX ON ORDERS (POSITION_ID);
CREATE  INDEX POSITION_GROUP_ID_INDEX ON ORDERS (POSITION_GROUP_ID);

-- --------------------- TABLE TRACKER ------------------------------------
CREATE TABLE POSITIONS_TRACKING  (
  ID int NOT NULL AUTO_INCREMENT,
  SIGNAL_ID varchar(20) NOT NULL,
  SIGNAL_GROUP_ID varchar(20) NOT NULL,
  POSITION_ID varchar(20) NOT NULL,
  POSITION_GROUP_ID varchar(20) NOT NULL,
  POSITION_TRACKING_ID varchar(20) NOT NULL,
  POSITION_TRACKING_GROUP_ID varchar(20) NOT NULL,
  MONEYNESS varchar(20) NOT NULL,
  SYMBOL varchar(10) NOT NULL,
  EXPIRY_DATE  varchar(10) NOT NULL,
  STRIKE_PRICE decimal(10,5) NOT NULL,
  INSTRUMENT_TYPE ENUM ('PUT','CALL','FUTURES') NOT NULL,
  TRANSACTION_TYPE ENUM ('BUY','SELL') NOT NULL,
  ORDER_TYPE ENUM ('MARKET','LIMIT') NOT NULL,
  CONTRACT_TYPE varchar(30) NOT NULL,
  NUM_LOTS int NOT NULL,
  LOT_SIZE int NOT NULL,
  QUANTITY int NOT NULL,
  IS_ACTIVE bool NOT NULL DEFAULT 1,
  IS_SQUARE_OFF bool NOT NULL DEFAULT 0,
  MARGIN_OVERALL decimal(20,2) NOT NULL,
  ENTRY_PRICE decimal(20,2) NOT NULL,
  EXIT_PRICE decimal(20,2),
  CURRENT_PRICE decimal(20,2) NOT NULL,
  EXECUTION_PRICE decimal(20,2) NOT NULL,
  PARAMS JSON,
  UNREALIZED_PNL decimal(20,2) NOT NULL,
  REALIZED_PNL decimal(20,2),
  UNREALIZED_PNL_GROUP decimal(20,2) NOT NULL,
  REALIZED_PNL_GROUP decimal(20,2),
  NET_PNL_OVERALL decimal(20,2) NOT NULL,
  REALIZED_PNL_OVERALL decimal(20,2),
  ENTRY_DELTA varchar(20),
  ENTRY_NET_DELTA varchar(20),
  ENTRY_NET_DELTA_OVERALL varchar(20),
  CURRENT_DELTA varchar(20),
  CURRENT_NET_DELTA varchar(20),
  CURRENT_NET_DELTA_OVERALL varchar(20),
  ENTRY_GAMMA varchar(20),
  ENTRY_NET_GAMMA varchar(20),
  CURRENT_GAMMA varchar(20),
  CURRENT_NET_GAMMA varchar(20),
  ENTRY_IV varchar(20),
  ENTRY_IV_DIFF_PCT varchar(20),
  CURRENT_IV varchar(20),
  CURRENT_IV_DIFF_PCT varchar(20),
  NET_DELTA_THRESHOLD varchar(20),
  ENTRY_THETA varchar(20),
  CURRENT_THETA varchar(20),
  ENTRY_NET_THETA varchar(20),
  CURRENT_NET_THETA varchar(20),
  ENTRY_VEGA varchar(20),
  CURRENT_VEGA varchar(20),
  ENTRY_NET_VEGA varchar(20),
  CURRENT_NET_VEGA varchar(20),
  CONTRACT_EXPIRY_DATE varchar(20),
  ENTRY_TIME_TO_EXPIRY varchar(20),
  CURRENT_TIME_TO_EXPIRY varchar(20),
  ORDER_MANIFEST varchar(500),
  TIME_VALUE_OPTIONS varchar(20),
  ENTRY_UNDERLYING varchar(20),
  CURRENT_UNDERLYING varchar(20),
  EXPECTED_THETA_PNL_PENDING varchar(20),
  CURRENT_THETA_PNL_PENDING varchar(20),
  NET_PNL_THRESHOLD varchar(20),
  ENTRY_ATM_PUT_PRICE decimal(20,2),
  ENTRY_ATM_CALL_PRICE decimal(20,2),
  ENTRY_ATM_AVG_PRICE decimal(20,2),
  ENTRY_ATM_PRICE_DIFF decimal(20,2),
  CURRENT_PRICE_PNL_PCT decimal(20,2),
  ENTRY_VIX decimal(20,2),
  CREATED_DATE_TIME TIMESTAMP DEFAULT NOW(),
  UPDATED_DATE_TIME TIMESTAMP ON UPDATE NOW(),
  PRIMARY KEY (ID)
);
CREATE  INDEX POSITION_SIGNAL_ID_INDEX ON POSITIONS_TRACKING (SIGNAL_ID);
CREATE  INDEX POSITION_SIGNAL_GROUP_ID_INDEX ON POSITIONS_TRACKING (SIGNAL_GROUP_ID);
CREATE  INDEX POSITION_ID_INDEX ON POSITIONS_TRACKING (POSITION_ID);
CREATE  INDEX POSITION_GROUP_ID_INDEX ON POSITIONS_TRACKING (POSITION_GROUP_ID);
CREATE  INDEX POSITION_TRACKING_ID_INDEX ON POSITIONS_TRACKING (POSITION_TRACKING_ID);
CREATE  INDEX POSITION_TRACKING_GROUP_ID_INDEX ON POSITIONS_TRACKING (POSITION_TRACKING_GROUP_ID);
CREATE  INDEX SYMBOL_INDEX ON POSITIONS_TRACKING (SYMBOL);
CREATE  INDEX CONTRACT_TYPE_INDEX ON POSITIONS_TRACKING (CONTRACT_TYPE);


-- --------------------- TABLE POSITIONS_BACK_UP ------------------------------------
CREATE TABLE POSITIONS_BACK_UP AS SELECT * FROM POSITION;

-- --------------------- TABLE POSITIONS_BACK_UP ------------------------------------
CREATE TABLE POSITIONS_TRACKING_BACK_UP AS SELECT * FROM POSITIONS_TRACKING;



