import enum

class InstrumentTypeEnum(enum.Enum):
    PUT = "PUT"
    CALL = "CALL"
    FUTURES = "FUTURES"

class TransactionTypeEnum(enum.Enum):
    BUY = "BUY"
    SELL = "SELL"

class OrderTypeEnum(enum.Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"

class AdjustmentTypeEnum(enum.Enum):
    CALL_ADJUSTMENT_SQUAREOFF = "CALL_ADJUSTMENT_SQUAREOFF"
    PUT_ADJUSTMENT_SQUAREOFF = "PUT_ADJUSTMENT_SQUAREOFF"
    FUT_BUY_FRESH_POSITION = "FUT_BUY_FRESH_POSITION"
    FUT_SELL_FRESH_POSITION = "FUT_SELL_FRESH_POSITION"
    FUT_BUY_ADJUSTMENT_SQUAREOFF = "FUT_BUY_ADJUSTMENT_SQUAREOFF"
    FUT_SELL_ADJUSTMENT_SQUAREOFF = "FUT_SELL_ADJUSTMENT_SQUAREOFF"